{{- if .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inadev
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: inadev
    alb.ingress.kubernetes.io/ingress.class: {{ .Values.ingress.ingressClass }}
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.loadBalancerScheme }}
    # alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.targetType }}
    alb.ingress.kubernetes.io/healthcheck-protocol: {{ .Values.ingress.healthCheckProtocol }}
    alb.ingress.kubernetes.io/healthcheck-port: '{{ .Values.ingress.healthCheckPort }}'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '{{ .Values.ingress.healthCheckIntervalSeconds }}'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '{{ .Values.ingress.healthCheckTimeoutSeconds }}'
    alb.ingress.kubernetes.io/success-codes: '{{ .Values.ingress.successCodes }}'
    alb.ingress.kubernetes.io/healthy-threshold-count: '{{ .Values.ingress.healthyThresholdCount }}'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '{{ .Values.ingress.unhealthyThresholdCount }}'
    alb.ingress.kubernetes.io/listen-ports: {{ .Values.ingress.sslPorts | toJson | quote }}
    # alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn | quote }}
    # alb.ingress.kubernetes.io/ssl-policy: {{ .Values.ingress.sslPolicy | quote }}
    # alb.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.sslRedirect | quote }}
    # external-dns.alpha.kubernetes.io/hostname: '{{ .Values.ingress.externalDnsHostname }}'
spec:
  ingressClassName: inadev
  defaultBackend:
    service:
      name: jenkins
      port:
        number: 8080
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jenkins
                port:
                  number: 8080
{{- end }}