apiVersion: v1
kind: Service
metadata:
  name: jenkins
  # namespace: {{ .Values.namespace }}
  labels:
    app: jenkins
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

